# 📊 Data Cleaning

## 📌 Topics Covered
- Handaling Missing Values
- Handaling Duplicate Data

---

## 🔹 Handling Missing Values

Missing values occur when no data is stored for a particular observation.

### ✅ Common Functions:
- isnull()
- dropna()
- fillna()
- ffill()
- bfill()

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("..//DataSets/raw_data.csv")
df.isnull()  # or we can use .isna()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [3]:
df.isnull().sum()   #gives total number of null values in overall column

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [4]:
#drop is used to remove all the rows/columns that contain null values.
df.dropna()  #this is for row 
df.dropna(axis = 1)  # this is for column

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [5]:
cleaned_data = df.copy()
mean_age = cleaned_data["age"].mean()
cleaned_data["age"] = cleaned_data["age"].fillna(mean_age)
cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [6]:
df.ffill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [7]:
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [8]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

## 🔹 Handling Duplicate Data

Duplicate data refers to repeated rows in a DataFrame.

In [9]:
df.duplicated()
df["country"].duplicated()
df[["country", "gender"]].duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [10]:
df.drop_duplicates()
#df.drop_duplicates(inplace = True) ....... to do changes directly in the main data .
#we always make a copy and do necessory changes , we avoid directly doing to main data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [11]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [12]:
#data types

In [13]:
df.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [14]:
df2 = df.copy()
df2["age"] = df2["age"].fillna(0)
df2["age"] = df2["age"].astype("int64")

df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

## 💡 Notes/Summary

- Use `isnull()` to detect missing values
- Use `dropna()` to remove missing data
- Use `fillna()` to replace missing values
- Use `ffill()` and `bfill()` for sequential data filling
- Use `duplicated()` to identify duplicates
- Use `drop_duplicates()` to remove duplicates

In [15]:
# reffer notes and must see the use of to_datetime()

In [16]:
# data cleaning for string reffer notes