# 📊 Feature Engineering & Data Transformation in Pandas

## 📌 Topics Covered

- Creating New Features
- apply()
- map()
- assign()
- replace()
- rename()
- Sorting Data
- Resetting Index
- Ranking
- Reordering Columns
- Data Cleaning Pipeline
- GroupBy Aggregation

---

## 🔹 Creating New Features

Feature Engineering is the process of creating new features (columns) from existing data to improve analysis or machine learning models.

### ✅ Using apply()

In [9]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"../DataSets/raw_data.csv")

df2 = df.copy()

# method 1 (this is preferable)
df2["tax"] = df2["income"].apply(lambda x : "20%" if x>= 60_000 else "10%")

# method 2 (using normal function)

# def tax_value(x):
#     if x >= 60_000:
#         return "20%"
#     else : 
#         return "10%"

# df2["tax"] = df2["income"].apply(tax_value)

df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  10%
1    1      John Doe  29.0     USA     Male  55000.0  10%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  10%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  10%

### 💡 Notes

- Can use lambda functions.
- Can use normal user-defined functions.
- `apply()` is a Higher Order Function because it accepts another function as an argument.

---

## 🔹 Mapping Values

`map()` is used to transform values according to a dictionary.

In [10]:
gender_map = {"Male": "M", "Female": "F", "Unknown": "U"}
df2["gender"] = df2["gender"].map(gender_map)
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%

### 💡 Notes

- Useful for encoding categorical values.
- Dictionary keys are replaced by corresponding values.

---

## 🔹 Creating Columns with assign()

`assign()` creates new columns without modifying the original DataFrame.

In [11]:
df2 = df2.assign(new_income = df2["income"]*1.1)
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%     63800.0

## 🔹 Replacing Values

`replace()` replaces specific values in a DataFrame.

In [12]:
df2["country"] = df2["country"].replace("USA", "US")
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

## 🔹 Renaming Labels

### Rename Columns

In [13]:
df2.rename(columns = {"income": "salary" , "gender": "sex"} )

    id          name   age country  sex   salary  tax  new_income
0    1      John Doe  29.0      US    M  55000.0  10%     60500.0
1    1      John Doe  29.0      US    M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada    F  62000.0  20%     68200.0
3    3          Alex   NaN      US    U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain    F      NaN  10%         NaN
5    5        Li Wei  27.0   China    M  51000.0  10%     56100.0
6    6           NaN  45.0   India    F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN    M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US    F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico    M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US  NaN  58000.0  10%     63800.0

### Rename Index

In [14]:
df2.rename(index = {1:"first"})

       id          name   age country gender   income  tax  new_income
0       1      John Doe  29.0      US      M  55000.0  10%     60500.0
first   1      John Doe  29.0      US      M  55000.0  10%     60500.0
2       2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3       3          Alex   NaN      US      U  47000.0  10%     51700.0
4       4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5       5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6       6           NaN  45.0   India      F  73000.0  20%     80300.0
7       7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8       8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9       9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10     10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

### 💡 Notes

- Does not modify the original DataFrame unless `inplace=True`.

---

## 🔹 Sorting Data

### Sort by Values

In [15]:
sorted_data = df2.sort_values("income")
sorted_data

    id          name   age country gender   income  tax  new_income
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN

### Sort by Index

In [16]:
sorted_data.sort_index()

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

### 💡 Notes

- Default sorting order is ascending.
- Use `ascending=False` for descending order.

---

## 🔹 Resetting Index

In [17]:
sorted_data.reset_index()

# we can see pandas has created another index . 
# if we want to drop the original index then we can , 
# sorted_data.reset_index(drop = True)

    index  id          name   age country gender   income  tax  new_income
0       9   9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
1       3   3          Alex   NaN      US      U  47000.0  10%     51700.0
2       5   5        Li Wei  27.0   China      M  51000.0  10%     56100.0
3       0   1      John Doe  29.0      US      M  55000.0  10%     60500.0
4       1   1      John Doe  29.0      US      M  55000.0  10%     60500.0
5      10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0
6       2   2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
7       8   8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
8       7   7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
9       6   6           NaN  45.0   India      F  73000.0  20%     80300.0
10      4   4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN

### 💡 Notes

- Creates a fresh index.
- Old index becomes a column unless dropped.

---

## 🔹 Ranking Data

Ranking assigns an order based on column values.

In [18]:
sorted_data["Ranking"] = sorted_data["income"].rank()
#sorted_data["Ranking"] = sorted_data["income"].rank(ascending = False , method="max")

sorted_data

    id          name   age country gender   income  tax  new_income  Ranking
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0      1.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0      2.0
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0      3.0
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0      4.5
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0      4.5
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0      6.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0      7.5
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0      7.5
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0      9.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0     10.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN      NaN

## 🔹 Reordering Columns

In [19]:
sorted_data[["id","name","age","country","gender","income","Ranking","tax","new_income"]]

    id          name   age country gender   income  Ranking  tax  new_income
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0      1.0  10%     49500.0
3    3          Alex   NaN      US      U  47000.0      2.0  10%     51700.0
5    5        Li Wei  27.0   China      M  51000.0      3.0  10%     56100.0
0    1      John Doe  29.0      US      M  55000.0      4.5  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0      4.5  10%     60500.0
10  10   Emily Davis  31.0      US    NaN  58000.0      6.0  10%     63800.0
2    2    Jane Smith   NaN  Canada      F  62000.0      7.5  20%     68200.0
8    8    Rachel Lee  29.0      US      F  62000.0      7.5  20%     68200.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0      9.0  20%     74800.0
6    6           NaN  45.0   India      F  73000.0     10.0  20%     80300.0
4    4  Maria Garcia  34.0   Spain      F      NaN      NaN  10%         NaN

In [20]:
df2 = df.copy()

required_flow = [col for col in df2.columns if col != "id"]+["id"]
print(required_flow)
df2[required_flow]

['name', 'age', 'country', 'gender', 'income', 'id']

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

## 🔹 Write data to csv

In [21]:
df2 = df.copy()

df2 = df2.drop_duplicates()
df2 = df2.fillna(0)
df2 = df2.sort_values("income")
df2 = df2.reset_index(drop=True)
df2.to_csv("sorted_data.csv")
df2

   id          name   age country   gender   income
0   4  Maria Garcia  34.0   Spain   Female      0.0
1   9   Carlos Ruiz   0.0  Mexico     Male  45000.0
2   3          Alex   0.0     USA  Unknown  47000.0
3   5        Li Wei  27.0   China     Male  51000.0
4   1      John Doe  29.0     USA     Male  55000.0
5  10   Emily Davis  31.0     USA        0  58000.0
6   2    Jane Smith   0.0  Canada   Female  62000.0
7   8    Rachel Lee  29.0     USA   Female  62000.0
8   7    Ahmed Khan  38.0       0     Male  68000.0
9   6             0  45.0   India   Female  73000.0

## 🔹 GroupBy Aggregation

`groupby()` is used to split data into groups and perform calculations.

In [22]:
df.groupby("country")["income"].mean()
df.groupby("country")["income"].min()
df.groupby("country")["income"].max()

df.groupby("gender")["income"].max()

gender
Female     73000.0
Male       68000.0
Unknown    47000.0
Name: income, dtype: float64

## 🔹 Multiple Aggregations

### Using aggregate()

In [23]:
df.groupby("country")["income"].aggregate(["mean", "max", "min"])
df.groupby("country")["income"].aggregate(avg_income= "mean", max_income = "max", min_income= "min")

         avg_income  max_income  min_income
country
Canada      62000.0     62000.0     62000.0
China       51000.0     51000.0     51000.0
India       73000.0     73000.0     73000.0
Mexico      45000.0     45000.0     45000.0
Spain           NaN         NaN         NaN
USA         55400.0     62000.0     47000.0

## 🔹 Aggregating Multiple Columns

### Dictionary Style

In [24]:
df.groupby("country").agg({
    "income": "max",
    "age": "min"
})

          income   age
country
Canada   62000.0   NaN
China    51000.0  27.0
India    73000.0  45.0
Mexico   45000.0   NaN
Spain        NaN  34.0
USA      62000.0  29.0

### Named Aggregation Style

In [25]:
df.groupby("country").agg(
    max_income = ("income", "max"),
    min_age= ("age", "min")
)

         max_income  min_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         62000.0     29.0

## 💡 Notes/Summary

- `apply()` → Apply custom functions to data.
- `map()` → Replace values using a dictionary.
- `assign()` → Create new columns.
- `replace()` → Standardize or modify values.
- `rename()` → Change column or index names.
- `sort_values()` → Sort rows using column values.
- `sort_index()` → Sort using index.
- `reset_index()` → Create a fresh index.
- `rank()` → Assign rankings.
- `groupby()` → Split data into groups.
- `agg()` / `aggregate()` → Perform multiple aggregations.