# 📊 Data Reshaping in Pandas

## 📌 Topics Covered
- Melt
- Pivot

---

## 🔹 Melt

`melt()` converts data from **wide format** to **long format**.

### ✅ Common Parameters
- `id_vars`
- `value_vars`
- `var_name`
- `value_name`

## 🔹 Pivot

`pivot()` converts data from **long format** to **wide format**.

### ✅ Common Parameters
- `index`
- `columns`
- `values`

---

In [1]:

import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Country" : ["USA", "USA", "India", "India"],
    "Year" : [2020, 2021, 2020, 2021],
    "Sales" : [100 , 120, 90 , 110],
    "Profit" : [20 , 25, 18, 22]
})

melted_df = df.melt(
    id_vars=["Country", "Year"],   
    value_vars=["Sales", "Profit"],
    var_name="Metrix",
    value_name="Values"   
)

melted_df.pivot(
    index=["Country", "Year"],
    columns="Metrix",
    values="Values"
)

Metrix        Profit  Sales
Country Year
India   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120

In [3]:
melted_df

  Country  Year  Metrix  Values
0     USA  2020   Sales     100
1     USA  2021   Sales     120
2   India  2020   Sales      90
3   India  2021   Sales     110
4     USA  2020  Profit      20
5     USA  2021  Profit      25
6   India  2020  Profit      18
7   India  2021  Profit      22

In [4]:
df

  Country  Year  Sales  Profit
0     USA  2020    100      20
1     USA  2021    120      25
2   India  2020     90      18
3   India  2021    110      22